//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher.Security {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Security.ISecurity_Service")]
    public interface ISecurity_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity_Service/Login", ReplyAction="http://tempuri.org/ISecurity_Service/LoginResponse")]
        bool Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity_Service/Login", ReplyAction="http://tempuri.org/ISecurity_Service/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity_Service/GetAccessToSystem", ReplyAction="http://tempuri.org/ISecurity_Service/GetAccessToSystemResponse")]
        void GetAccessToSystem(string username, string email, string unhashed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity_Service/GetAccessToSystem", ReplyAction="http://tempuri.org/ISecurity_Service/GetAccessToSystemResponse")]
        System.Threading.Tasks.Task GetAccessToSystemAsync(string username, string email, string unhashed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity_Service/GetString", ReplyAction="http://tempuri.org/ISecurity_Service/GetStringResponse")]
        int GetString(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity_Service/GetString", ReplyAction="http://tempuri.org/ISecurity_Service/GetStringResponse")]
        System.Threading.Tasks.Task<int> GetStringAsync(int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurity_ServiceChannel : Launcher.Security.ISecurity_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Security_ServiceClient : System.ServiceModel.ClientBase<Launcher.Security.ISecurity_Service>, Launcher.Security.ISecurity_Service {
        
        public Security_ServiceClient() {
        }
        
        public Security_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Security_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Security_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Security_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public void GetAccessToSystem(string username, string email, string unhashed) {
            base.Channel.GetAccessToSystem(username, email, unhashed);
        }
        
        public System.Threading.Tasks.Task GetAccessToSystemAsync(string username, string email, string unhashed) {
            return base.Channel.GetAccessToSystemAsync(username, email, unhashed);
        }
        
        public int GetString(int number) {
            return base.Channel.GetString(number);
        }
        
        public System.Threading.Tasks.Task<int> GetStringAsync(int number) {
            return base.Channel.GetStringAsync(number);
        }
    }
}
